openapi: 3.1.0
x-stoplight:
  id: p7hu90o4j4x4x
info:
  title: ml
  version: '1.0'
  summary: Documentation for the ML part of the API.
servers:
  - url: 'http://localhost:8000/api/v1/ml'
    description: local
paths:
  /training/train-models:
    post:
      summary: trainModels
      tags: []
      responses: {}
      operationId: trainModels
components:
  schemas: {}
