services:
  angular:
    container_name: angular
    build:
      context: ./angular
      dockerfile: Dockerfile
    networks:
      - project-network
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/usr/src/app
    command: npm start
    depends_on:
      - laravel

  laravel:
    container_name: laravel
    build:
      context: ./laravel
      dockerfile: Dockerfile
    networks:
      - project-network
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - shared:/var/www/storage/app/shared # Mount the shared volume
    depends_on:
      - db

  ml:
    container_name: ml
    build:
      context: ./ml-microservice
      dockerfile: Dockerfile
    networks:
      - project-network
    ports:
      - "5002:5002"
    volumes:
      - ./ml-microservice:/usr/src/app
      - shared:/usr/src/app/shared # Mount the shared volume
    env_file:
      - ./ml-microservice/.env

  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    networks:
      - project-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: final-project
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data:
  shared: # Shared volume definition for data

networks:
  project-network:
    driver: bridge
    external: true
    name: project-module-2024-apr-mireiatz_default