openapi: 3.1.0
x-stoplight:
  id: uz2jxosmmw8mw
info:
  title: Project Module 2024 Apr Mireia TZ
  version: '1.0'
  contact:
    name: Mireia
  description: API spec
servers:
  - url: 'http://localhost:8000/api/v1'
    description: local
paths:
  /categories:
    get:
      summary: getCategories
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/CategoriesResponse'
      operationId: getCategories
      description: ''
  /inventory-transactions:
    get:
      summary: getInventoryTransactions
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/InventoryTransactionsResponse'
      operationId: getInventoryTransactions
  /orders:
    get:
      summary: getOrders
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OrdersResponse'
      operationId: getOrders
  /products:
    get:
      summary: getProducts
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/ProductsResponse'
      operationId: getProducts
    post:
      summary: ''
      operationId: searchCategories
      responses:
        '200':
          description: OK
      description: ''
  /providers:
    get:
      summary: getProviders
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/ProvidersResponse'
      operationId: getProviders
  /sales:
    get:
      summary: getSales
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/SalesResponse'
      operationId: getSales
  /stores:
    get:
      summary: getStores
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/StoresResponse'
      operationId: getStores
  /analytics/overview:
    parameters: []
    post:
      summary: ''
      operationId: getOverviewMetrics
      responses:
        '200':
          $ref: '#/components/responses/OverviewMetricsResponse'
      requestBody:
        $ref: '#/components/requestBodies/GetOverviewMetricsRequest'
components:
  schemas:
    Category:
      title: Category
      x-stoplight:
        id: qhj2dzcqn3d0q
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-stoplight:
            id: d75udpyqtdlwr
        description:
          type: string
          x-stoplight:
            id: j3ritysfc0vlr
    InventoryTransaction:
      title: InventoryTransaction
      x-stoplight:
        id: xherxzcwr1j2g
      type: object
      properties:
        id:
          type: string
        store_id:
          type: string
          x-stoplight:
            id: 5axiabblwp2dy
          format: uuid
        parent_id:
          type: string
          x-stoplight:
            id: l19sqph5twl5r
          format: uuid
        parent_type:
          type: string
          x-stoplight:
            id: qbllxce2iey19
        product_id:
          type: string
          x-stoplight:
            id: ydlrkzyqeqdim
          format: uuid
        quantity:
          type: integer
          x-stoplight:
            id: inzzoxkxuv4ly
        stock_balance:
          type: integer
          x-stoplight:
            id: tuxw2q7u9h0z7
    Order:
      title: Order
      x-stoplight:
        id: hkulfcra66atc
      type: object
      properties:
        id:
          type: string
          format: uuid
        store_id:
          type: string
          x-stoplight:
            id: hbd3qve6012sc
          format: uuid
        provider_id:
          type: string
          x-stoplight:
            id: e3zdonuqfazhl
          format: uuid
        date:
          type: string
          x-stoplight:
            id: 9tef4iz6254xo
          format: date-time
        cost:
          type: integer
          x-stoplight:
            id: am6pc5b20d8hb
    Product:
      title: Product
      x-stoplight:
        id: xcn85zxonfn92
      type: object
      properties:
        id:
          type: string
        category_id:
          type: string
          x-stoplight:
            id: 7u097e4yobwqr
          format: uuid
        provider_id:
          type: string
          x-stoplight:
            id: t7tfymnsicx65
          format: uuid
        name:
          type: string
          x-stoplight:
            id: vc491liveu9mv
        description:
          type: string
          x-stoplight:
            id: 73oacbjrr2mpp
        unit:
          type: string
          x-stoplight:
            id: vco6h78rz5a5p
        amount_per_unit:
          type: integer
          x-stoplight:
            id: b1co71e415bzj
        min_stock_level:
          type: integer
          x-stoplight:
            id: yqdm1d1252mtv
        max_stock_level:
          type: string
          x-stoplight:
            id: aqgyetgjup73f
        sale:
          type: integer
          x-stoplight:
            id: 58pns7c6y2mqn
        cost:
          type: integer
          x-stoplight:
            id: xzrnpjgpdl0kh
        currency:
          type: string
          x-stoplight:
            id: oqkcxrnquktdl
    Provider:
      title: Provider
      x-stoplight:
        id: 2ikd05bpg1jno
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-stoplight:
            id: x3pfnagk1cahy
        description:
          type: string
          x-stoplight:
            id: 4l3mol2fkoren
        phone:
          type: string
          x-stoplight:
            id: r2dktlr8pp6t9
        email:
          type: string
          x-stoplight:
            id: ess1dov77ht1c
        address:
          type: object
          x-stoplight:
            id: bito634v88915
        lead_days:
          type: integer
          x-stoplight:
            id: un7jlcpw9aqd1
    Sale:
      title: Sale
      x-stoplight:
        id: 1t5wn9xhvdsiy
      type: object
      properties:
        id:
          type: string
        store_id:
          type: string
          x-stoplight:
            id: oiu1pwqncgqu9
          format: uuid
        date:
          type: string
          x-stoplight:
            id: ehzsjzi9z8gte
          format: date-time
        sale:
          type: integer
          x-stoplight:
            id: dqdfuyktra348
        cost:
          type: integer
          x-stoplight:
            id: monvlj6lr9g25
        vat:
          type: integer
          x-stoplight:
            id: 2qewr5f576fhk
        net_sale:
          type: integer
          x-stoplight:
            id: z2gdh7sb6gt70
        margin:
          type: integer
          x-stoplight:
            id: 4i2x5yrjwplec
        currency:
          type: string
          x-stoplight:
            id: 2v9wqjpbuzygi
    Store:
      title: Store
      x-stoplight:
        id: w1zbddw9ssupq
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          x-stoplight:
            id: 72p309gryj2n5
        location:
          type: string
          x-stoplight:
            id: 4ba6o1g62mgov
    OverviewMetrics:
      title: OverviewMetrics
      x-stoplight:
        id: 0wn9kcxb71v38
      type: object
      properties:
        stock:
          type: object
          x-stoplight:
            id: rg05f2q9whb1s
          required:
            - products_in_stock_count
            - products_out_of_stock_count
            - critically_low_stock_products
            - excessive_stock_products
            - inventory_value
          properties:
            products_in_stock_count:
              type: integer
              x-stoplight:
                id: rj8gui87mi2mf
            products_out_of_stock_count:
              type: integer
              x-stoplight:
                id: ctg94ixgf3116
            critically_low_stock_products:
              type: array
              x-stoplight:
                id: vfj9n4gecuy5m
              items:
                x-stoplight:
                  id: u7jaoogpsj0il
                type: string
            excessive_stock_products:
              type: array
              x-stoplight:
                id: 5jmtqimmkjuu9
              items:
                x-stoplight:
                  id: la2nfxnqtcouu
                type: string
            inventory_value:
              type: number
              x-stoplight:
                id: 21ioezpboe48k
        sales:
          type: object
          x-stoplight:
            id: 9znhnemy5ttur
          required:
            - number_of_sales
            - total_items_sold
            - total_sales_value
            - highest_sale
            - lowest_sale
            - sale_with_most_items
            - sale_with_least_items
          properties:
            number_of_sales:
              type: integer
              x-stoplight:
                id: 486pk1ps60pn0
            total_items_sold:
              type: integer
              x-stoplight:
                id: zsf9l19jhsbxy
            total_sales_value:
              type: number
              x-stoplight:
                id: ue6ssf7q98d08
            highest_sale:
              type: number
              x-stoplight:
                id: 6x9ylbfqlr4gb
            lowest_sale:
              type: number
              x-stoplight:
                id: p8q3kk8xttg3a
            sale_with_most_items:
              type: integer
              x-stoplight:
                id: glh4seevm33gh
            sale_with_least_items:
              type: integer
              x-stoplight:
                id: z2hbeotq49vkb
        product_performance:
          type: object
          x-stoplight:
            id: fmmgl4oide3h2
          required:
            - top_selling_products
            - least_selling_products
            - highest_revenue_products
            - lowest_revenue_products
          properties:
            top_selling_products:
              type: array
              x-stoplight:
                id: 4y94ehn7shcip
              items:
                x-stoplight:
                  id: 6rr4atmssnt8k
                type: string
            least_selling_products:
              type: array
              x-stoplight:
                id: 4zw07uyan0b00
              items:
                x-stoplight:
                  id: ek8n841y6lbet
                type: string
            highest_revenue_products:
              type: array
              x-stoplight:
                id: y90upzs2b018d
              items:
                x-stoplight:
                  id: 6yvp2pppybivv
                type: string
            lowest_revenue_products:
              type: array
              x-stoplight:
                id: cjtdgzcpyxlav
              items:
                x-stoplight:
                  id: 5y2a2qrmsjxb5
                type: string
      required:
        - stock
        - sales
        - product_performance
  responses:
    CategoriesResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                x-stoplight:
                  id: 2tgwrqr4yufcb
                type: array
                items:
                  $ref: '#/components/schemas/Category'
                  x-stoplight:
                    id: n7ffcabpxlpmf
              success:
                type: boolean
                x-stoplight:
                  id: zpwmzuhcw1b5u
              errors:
                type: object
                x-stoplight:
                  id: mbdtpv0j8o8yp
    InventoryTransactionsResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                x-stoplight:
                  id: tfi2lpglp1ty1
                items:
                  $ref: '#/components/schemas/InventoryTransaction'
                  x-stoplight:
                    id: ivtg2dgcmj1mc
              success:
                type: boolean
                x-stoplight:
                  id: 7yzhh25djc1pg
              errors:
                type: object
                x-stoplight:
                  id: vxr4q9ua1qedg
    OrdersResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                x-stoplight:
                  id: 5q3uisi1p8aty
                items:
                  $ref: '#/components/schemas/Order'
                  x-stoplight:
                    id: vy8jy8v8krhu1
              success:
                type: boolean
                x-stoplight:
                  id: ebf1yu8ynvewc
              errors:
                type: object
                x-stoplight:
                  id: p7sie6guucmka
    ProductsResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                x-stoplight:
                  id: l5dv7bfrpxtln
                items:
                  $ref: '#/components/schemas/Product'
                  x-stoplight:
                    id: 04s4h9hzybz14
              success:
                type: boolean
                x-stoplight:
                  id: l84qk0qgudj9o
              errors:
                type: object
                x-stoplight:
                  id: xm0ruprho6im3
    ProvidersResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                x-stoplight:
                  id: t84r5hu8x73u1
                items:
                  $ref: '#/components/schemas/Provider'
                  x-stoplight:
                    id: 4nhqpakjfv6z3
              success:
                type: boolean
                x-stoplight:
                  id: 0k2r7tv66k48n
              errors:
                type: object
                x-stoplight:
                  id: 9g1wka7euisof
    SalesResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                x-stoplight:
                  id: a6plhltgjvep6
                items:
                  $ref: '#/components/schemas/Sale'
                  x-stoplight:
                    id: mw5t6ofgstksv
              success:
                type: boolean
                x-stoplight:
                  id: 10uwiber03w2x
              errors:
                type: object
                x-stoplight:
                  id: pb9dtmf8tcfyv
    StoresResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                x-stoplight:
                  id: oxytph2nob5a5
                items:
                  $ref: '#/components/schemas/Store'
                  x-stoplight:
                    id: jp784zqkusjud
              success:
                type: boolean
                x-stoplight:
                  id: bzxmyjtgg218n
              errors:
                type: object
                x-stoplight:
                  id: xem82ok03vkrq
    OverviewMetricsResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/OverviewMetrics'
                x-stoplight:
                  id: 2rm6a9mxa269d
              success:
                type: boolean
                x-stoplight:
                  id: dz986bu60nix9
              errors:
                type: object
                x-stoplight:
                  id: av5spbhpqn7ba
            required:
              - data
              - success
  requestBodies:
    GetOverviewMetricsRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              period:
                type: string
                x-stoplight:
                  id: fmygbj9kc2aiu
            required:
              - period
